export const MEKNES_NEIGHBORHOODS = [
    "Hamria",
    "Mansour",
    "Toulal",
    "Sidi Baba",
    "Berradi",
    "Ouislane",
    "Marjane",
    "Bassatine",
    "Plaisance",
    "Zeitoune",
    "Rouamzine",
    "Agdal",
    "Belle Vue",
    "Anfa",
    "Sidi Bouzekri",
    "Bni M'Hamed",
    "Sidi Said",
    "Riad",
    "Wafae",
    "Nahda",
    "Salam",
    "Zitoune",
    "Koulouch"
].sort();
